name: tests

on:
  push:
    branches:
      - master
      - main
      - unified
  pull_request:
    branches_ignore: []

jobs:
  Dry Run and Lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker://snakemake/snakemake:v5.24.2
    - name: Tumor-normal FastQ Dry Run
      run: |
        docker run -v $PWD:/opt2 snakemake/snakemake:v5.24.2 \
        /opt2/exome-seek run --input \
        /opt2/.tests/Sample10_ARK1_S37.R1.fastq.gz /opt2/.tests/Sample10_ARK1_S37.R2.fastq.gz \
        /opt2/.tests/Sample11_ACI_158_S38.R1.fastq.gz /opt2/.tests/Sample11_ACI_158_S38.R2.fastq.gz \
        /opt2/.tests/Sample4_CRL1622_S31.R1.fastq.gz /opt2/.tests/Sample4_CRL1622_S31.R2.fastq.gz \
        --output /opt2/output_tn_fqs --targets /opt2/.tests/Agilent_SSv7_allExons_hg38.bed \
        --pairs /opt2/.tests/pairs.tsv --genome hg38 --mode local --ffpe --cnv --dry-run
    - name: Tumor-only FastQ Dry Run
      run: |
        docker run -v $PWD:/opt2 snakemake/snakemake:v5.24.2 \
        /opt2/exome-seek run --input \
        /opt2/.tests/Sample10_ARK1_S37.R1.fastq.gz /opt2/.tests/Sample10_ARK1_S37.R2.fastq.gz \
        /opt2/.tests/Sample11_ACI_158_S38.R1.fastq.gz /opt2/.tests/Sample11_ACI_158_S38.R2.fastq.gz \
        /opt2/.tests/Sample4_CRL1622_S31.R1.fastq.gz /opt2/.tests/Sample4_CRL1622_S31.R2.fastq.gz \
        --output /opt2/output_tonly_fqs --targets /opt2/.tests/Agilent_SSv7_allExons_hg38.bed \
        --genome hg38 --mode local --ffpe --dry-run
    - name: Tumor-normal BAM Dry Run
      run: |
        docker run -v $PWD:/opt2 snakemake/snakemake:v5.24.2 \
        /opt2/exome-seek run --input \
        /opt2/.tests/Sample10_ARK1_S37.recal.bam \
        /opt2/.tests/Sample11_ACI_158_S38.recal.bam \
        /opt2/.tests/Sample4_CRL1622_S31.recal.bam \
        --output /opt2/output_tn_bams --targets /opt2/.tests/Agilent_SSv7_allExons_hg38.bed \
        --pairs /opt2/.tests/pairs.tsv --genome hg38 --mode local --ffpe --cnv --dry-run
    - name: Tumor-only BAM Dry Run
      run: |
        docker run -v $PWD:/opt2 snakemake/snakemake:v5.24.2 \
        /opt2/exome-seek run --input \
        /opt2/.tests/Sample10_ARK1_S37.recal.bam \
        /opt2/.tests/Sample11_ACI_158_S38.recal.bam \
        /opt2/.tests/Sample4_CRL1622_S31.recal.bam \
        --output /opt2/output_tonly_bams --targets /opt2/.tests/Agilent_SSv7_allExons_hg38.bed \
        --genome hg38 --mode local --ffpe --dry-run
    - name: Lint Workflow
      continue-on-error: true
      run: |
        docker run -v $PWD:/opt2 snakemake/snakemake:v5.24.2 snakemake --lint -s /opt2/output/workflow/Snakefile -d /opt2/output_tn_fqs || \
        echo 'There may have been a few warnings or errors. Please read through the log to determine if its harmless.'
